// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLcksfNiSuK_MxsGevOz-ECWKBqLr7vvM',
    appId: '1:904915840480:web:eda0539df7ac405b5e8f85',
    messagingSenderId: '904915840480',
    projectId: 'g-demo-c6225',
    authDomain: 'g-demo-c6225.firebaseapp.com',
    storageBucket: 'g-demo-c6225.firebasestorage.app',
    measurementId: 'G-27MVQ3XV5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHLmHkGwJhwn5MMnY0Kh0MN5ysuQerKQ',
    appId: '1:904915840480:android:541a467b0e62d93f5e8f85',
    messagingSenderId: '904915840480',
    projectId: 'g-demo-c6225',
    storageBucket: 'g-demo-c6225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl6dv9stk_NasAwwmsunoFN1QVI6_cirw',
    appId: '1:904915840480:ios:1326f6c048605c9a5e8f85',
    messagingSenderId: '904915840480',
    projectId: 'g-demo-c6225',
    storageBucket: 'g-demo-c6225.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl6dv9stk_NasAwwmsunoFN1QVI6_cirw',
    appId: '1:904915840480:ios:1326f6c048605c9a5e8f85',
    messagingSenderId: '904915840480',
    projectId: 'g-demo-c6225',
    storageBucket: 'g-demo-c6225.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLcksfNiSuK_MxsGevOz-ECWKBqLr7vvM',
    appId: '1:904915840480:web:f0f438186c98abff5e8f85',
    messagingSenderId: '904915840480',
    projectId: 'g-demo-c6225',
    authDomain: 'g-demo-c6225.firebaseapp.com',
    storageBucket: 'g-demo-c6225.firebasestorage.app',
    measurementId: 'G-JM7ETQYGLS',
  );

}